test_test:
    resource: "@TestTestBundle/Controller/"
    type:     annotation
    prefix:   /


api:
    resource: "."
    type:     "api"
    prefix: /api

    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"

api_login_check:
    path: /api/login_check